Add cube control panel
ACON3D/ABLER pull request #110
Opened 2022-03-07 08:41 UTC by habijung

작업 중입니다.

2022-03-08 05:13 UTC, Youdiie commented on release/scripts/startup/abler/cube_control.py
> +        # Meaning?
context.object를 받아서 함수를 실행하는게 어떨까요?
(ACON_prop.cube_loaction_x)custom_properties보단 operator로 함수로 실행하는게 좋아보입니다!

2022-03-08 05:13 UTC, Youdiie commented on release/scripts/startup/abler/lib/cube.py
> +        cube_obj.location.x = loc_x
여기서 loc_x를 따로 둔 이유가 있을까요?
cube_obj.location.x = round(prop.cube_location_x,2)로 바로 가도 될거 같습니다~

2022-03-08 05:13 UTC, Youdiie commented on release/scripts/startup/abler/cube_control.py
> +        # Meaning?
라고 썼다가 prop update로 함수로 연결했군요; 요건 무시해주세요ㅎㅎ

2022-03-08 05:13 UTC, Youdiie commented on release/scripts/startup/abler/cube_control.py
> +    bl_idname = "acon3d.get_cube_object"
get_cube_object 기능이 굳이 필요할지 모르겠네요. 유저가 쓴다고해도 필요한 큐브를 직접 선택하고 파라미터를 조절할거 같아요!

2022-03-08 05:13 UTC, Youdiie commented on release/scripts/startup/abler/cube_control.py
> +                    obj_name += "." + format(n, "03")
format이 어떻게 들어가는걸까요? 요 문법 신기하네요!

2022-03-08 05:13 UTC, Youdiie commented on release/scripts/startup/abler/cube_control.py
> +                    cube_obj.location = (2, -2, 3)
location이 (2,-2,3)인 이유가 있을까요?

2022-03-08 05:13 UTC, Youdiie commented on release/scripts/startup/abler/cube_control.py
> +            print("Location : (" + str(cube_obj.location) + ")")
print에선 +보단 f-string이 읽히는데 좋더라구요!

2022-03-08 05:21 UTC, sdkfile commented on release/scripts/startup/abler/lib/cube.py
> +        cube_obj.location.x = loc_x
이거 제가 맨날 하는 잔소리네요 ㅋㅋㅋㅋ @Youdiie

2022-03-08 05:23 UTC, habijung commented on release/scripts/startup/abler/cube_control.py
> +
@Youdiie

"개체를 선택할 시" 라는게 특정 object를 클릭했을 때라는 의미일까요?
그럼 평소에는 비활성화 되어 있다가 object가 (여기서는 큐브) 선택되면 버튼이 활성화가 될까요?

2022-03-08 05:23 UTC, Youdiie commented on release/scripts/startup/abler/lib/cube.py
> +        cube_obj.location.x = loc_x
다 받은만큼 돌려드리는거 아니겠슴까~

2022-03-08 05:24 UTC, Youdiie commented on release/scripts/startup/abler/cube_control.py
> +
네 그게 ux 경험적으로 좋아 보입니다!

2022-03-08 08:48 UTC, sdkfile commented on release/scripts/startup/abler/cube_control.py
> +                    cube_obj.location = (2, -2, 3)
이거 제가 알기로는 startup.blend 코니방에서 작업하느라 안보여서 이렇게 옮긴거 같습니당 ㅋㅋ

2022-03-09 06:13 UTC, habijung commented on release/scripts/startup/abler/cube_control.py
> +        # Meaning?
@Youdiie 다음에는 다른 방법으로도 시도해보겠습니다!

2022-03-11 00:47 UTC, sdkfile commented
@habijung 이거는 유디님 리뷰 내용 기반으로 오늘 한번 수정해보는게 어떨까요? 머지는 하지 않을 예정이지만 컨플릭트도 해결해보고요 :)

2022-03-11 06:40 UTC, sdkfile reviewed
한번 리뷰 완료했습니당~

2022-03-11 06:40 UTC, sdkfile commented on release/scripts/startup/abler/cube_control.py
> -    bl_options = {"DEFAULT_CLOSED"}
이거는 왜 빠졌을까요?

2022-03-11 06:40 UTC, sdkfile commented on release/scripts/startup/abler/cube_control.py
> +
default closed 옵션을 달아주는게 일단 지금은 현황이라 (general 패널 제외) 달아주시는 게 좋을 것 같습니다~~

2022-03-11 06:52 UTC, habijung commented on release/scripts/startup/abler/cube_control.py
> -    bl_options = {"DEFAULT_CLOSED"}
@sdkfile 다시 업데이트 했습니다! 피드백 감사합니다.

2022-03-11 06:53 UTC, habijung commented
## 기능 업데이트 (22.03.11)

### 완료
---
- [x] Get Object Name 삭제 ▶ `print` 확인용이기 때문에 불필요하여 삭제
- [x] 내장함수 `poll` 을 사용해서 큐브가 생성되고 선택되었을 때만 Location / Scale 패널 활성화
- [x] Location / Scale 값은 `context.scene.ACON_prop` 의 `update` 로 유지
- [x] `cupe.py` 의 x, y, z 값 할당 가독성 수정
- [x] 큐브가 없을 때 삭제를 하면 큐브 생성해야한다는 문구를 `print` ▶`self.report` 로 변경

### 미완료
---
- [ ] Object를 `string`이 아닌 `pointer`로 구현
- [ ] `Viewport` 에서 큐브 값 수정할 때 `operator` 에 값 반영

### 결과
---
![image](https://user-images.githubusercontent.com/52474700/157817328-f92b0e76-e695-4ca8-99d4-3c00064ef416.png)

2022-03-11 06:55 UTC, sdkfile requested changes
마이너한 수정사항 전달드립니당~

2022-03-11 06:55 UTC, sdkfile commented on release/scripts/startup/abler/cube_control.py
> +        # Meaning?
이 주석도 딱히 의미는 없는 것 같은데 없어도 괜찮지 않을까요?

2022-03-11 06:55 UTC, sdkfile commented on release/scripts/startup/abler/cube_control.py
> +class Acon3dCubeLocationPanel(bpy.types.Panel):
마찬가지로 부모 패널 안에 들어가는 자식 패널들도 closed 옵션을 쓰는걸로 이야기가 되어있어서 세개의 패널 모두 수정해주시면 좋을 것 같습니다!

2022-03-11 06:55 UTC, sdkfile commented on release/scripts/startup/abler/cube_control.py
> +
해결 된 review thread의 경우에는 아래의 resolve conversation을 눌러서 리뷰 페이지 가독성을 높혀주시면 좋을 것 같습니다!

2022-03-11 07:04 UTC, habijung commented on release/scripts/startup/abler/cube_control.py
> +
@sdkfile 네! 알겠습니다. 조언 감사합니다.

2022-03-11 07:09 UTC, habijung commented
> 마이너한 수정사항 전달드립니당~

말씀하신 부분 수정해서 커밋 했습니다!

2022-03-11 07:12 UTC, sdkfile commented
지금까지 정도 내용이면 어프룹 나오는 정도의 내용인 것 같습니다! 고생하셨습니당. 
이거는 실제로 들어가는 커밋은 아니니 PR 닫도록 하겠습니다~!!

2022-03-11 07:12 UTC, closed without merging