login ID remember
acon3d/ABLER pull request #131
Opened 2021-11-01 05:07 UTC by Youdiie

UI location find

toggle changing

체크박스 상태로 userID.txt 생성 나눔

주석추가

login ID remember

2021-11-01 10:19 UTC, seungha-kim commented
내일 같이 커밋 정리 + Github에 이메일 연동까지 한번 가시죵!!

2021-11-01 10:59 UTC, sdkfile commented
추후 간결한 commit log를 위해서 gitignore에 조금 추가했슴다

2021-11-02 04:11 UTC, seungha-kim commented
오프라인에서 리뷰드린 내용 여기에도 적어놓습니다:
- 주석은 꼭 필요할 때만 커밋하는 것이 좋다
- 이메일 기억을 안 하는 사용자의 경우에도 userID 파일에 이메일을 남기고 있다. 선택을 안 한 사람의 경우 userID 파일 자체를 남기지 않는 것이 좋을 것이다

2021-11-02 04:15 UTC, Youdiie commented
댄님의 도움으로 전체 파일에서 필요한 부분만 stage에 올렸습니다!
스듴님 추가해주신 gitignore 커밋도 함께 올렸습니다.

2021-11-02 04:17 UTC, seungha-kim commented on release/scripts/startup/abler/custom_properties.py
> +    def toggle_remember_username(self, context):
toggle_remember_username 필요한 이유가 무엇일까용

2021-11-02 04:17 UTC, seungha-kim commented on release/scripts/startup/abler/credential_modal.py
> +        prop.username = ""
prop.username 의 기본값이 빈 문자열이라면 357 라인은 필요없는 것 아닐지 여쭤봅니당

2021-11-02 04:17 UTC, seungha-kim commented on release/scripts/startup/abler/credential_modal.py
> +                pass  # 파일 실제로 삭제할지 추후 고려
"checkbox 파일을 따로 두지 말고, userID 파일 유무만 가지고 아이디 저장 여부를 관리하자"라고 오프라인에서 제안 드렸었어용

2021-11-02 04:24 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +        prop.username = ""
네 확인해보니 빈 문자열이 기본값이라 삭제하겠습니다!

2021-11-02 04:27 UTC, Youdiie commented on release/scripts/startup/abler/custom_properties.py
> +    def toggle_remember_username(self, context):
toggle을 하기위한 기작이 요 함수라고 생각했는데 삭제하고도 잘 실행되는걸 보니 필요없는거 같습니다!

2021-11-02 04:47 UTC, seungha-kim commented
코드 리뷰 끝나고 나면, 첫 커밋에 git username, email 안들어간 부분 다시 넣기 위해 리셋&포스푸시 한번 더 갑시당

2021-11-02 06:03 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +                pass  # 파일 실제로 삭제할지 추후 고려
넵 아이디 저장의 체크박스 상태를 저장하는 파일을 따로 만들지 않고 userID 파일 유무로 체크박스 상태를 불러왔습니다.
추가로 에이블러를 맨 처음 실행했을 때(acon_session 파일이 없을때) 체크박스가 켜져있도록 기작도 추가했습니다.

2021-11-02 08:05 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +                )  # rememeber username checkbox UI
요기 주석도 지워도 될 것 같은 느낌입니닷~

2021-11-02 08:05 UTC, seungha-kim commented on release/scripts/startup/abler/lib/remember_id.py
> +
빈 줄 지워주세용~~

2021-11-02 08:05 UTC, seungha-kim approved these changes
사소한 것 제외하고는 좋아 보여서 어프루브 미리 누릅니닷! 고생 많으셨어요!

2021-11-02 08:34 UTC, Youdiie commented
댄님께서 말씀해주신 필요없는 주석, 빈줄 삭제했습니다!

2021-11-02 18:43 UTC, hoiekim requested changes

2021-11-02 18:43 UTC, hoiekim commented on release/scripts/startup/bl_operators/wm.py
> +                row.prop(
아래 이미지처럼 체크박스가 표시되는데 이 버튼이 `아이디 기억하기` 버튼인지 UI적으로 명쾌하지 않은 것 같습니다.

![image](https://user-images.githubusercontent.com/61715204/139921287-4c50301f-f214-4147-8fa9-90b5da6791b0.png)

아래 이미지는 구글 이미지검색으로 찾은 예시인데 이와 같은 사례가 많이 사용되어서 직관적으로 인식될 것 같습니다. 이렇게 변경하는 것은 어떨지 검토 부탁드립니다.

![image](https://user-images.githubusercontent.com/61715204/139922024-21743bf8-692d-4c40-bcec-fda63b173900.png)

2021-11-02 18:43 UTC, hoiekim commented on release/scripts/startup/abler/credential_modal.py
> +            read_remembered_checkbox()
이 함수는 boolean을 반환할 뿐 다른 일을 하는 것이 없는데.. 실수로 적은 것이 아닌가 싶어요

2021-11-02 18:43 UTC, hoiekim commented on release/scripts/startup/abler/credential_modal.py
> +    prop = userInfo.ACON_prop
`userInfo.Acon_prop` 객체를 따로 변수로 지정하려면 앞에 나오는 316번 줄, 340번 줄, 342번 줄도 같은 변수를 사용하는 것으로 수정하면 더 깔끔할 것 같습니다.

2021-11-02 18:43 UTC, hoiekim commented on release/scripts/startup/abler/credential_modal.py
> +        prop.remember_username = read_remembered_checkbox()
두가지 의문점이 있습니다.

1. `path_cookiesFile`은 `"acon3d_session"` 파일인데 이 세션데이터가 존재할 경우에만 `remembered_id`를 확인하는 것이 맞나요?? 굳이 그러지 않고 항상 `read_rememberd_checkbox()`를 실행하면 되지 않나요??
2. 326번 줄에서 이미 해당 경로의 파일(또는 폴더지만 의도상 파일)이 존재하는지 확인하기 때문에 굳이 다시 확인할 필요가 없지 않나요?? (대신 try 블록 안으로 옮겨야 함)

2021-11-02 18:43 UTC, hoiekim commented on release/scripts/startup/abler/credential_modal.py
> +        prop.username = read_remembered_id()
354번 줄과 342번 줄은 같은 역할을 하지 않나요??

2021-11-02 18:43 UTC, hoiekim commented on release/scripts/startup/abler/lib/remember_id.py
> +path_cookiesID = os.path.join(path_cookiesFolder, "userID")
`userID`, `id`, `username` 등이 혼용되고 있어서 가독성에 부정적인 영향을 미치는 것 같습니다. 모두 `username`으로 통일하는 것이 어떨지 제안합니다.

2021-11-03 02:37 UTC, Youdiie commented on release/scripts/startup/abler/lib/remember_id.py
> +path_cookiesID = os.path.join(path_cookiesFolder, "userID")
넵 모두 username으로 변경하겠습니다!

2021-11-03 02:38 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +            read_remembered_checkbox()
헉 넵 바로 수정하겠습니다!

2021-11-03 02:42 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +    prop = userInfo.ACON_prop
넵 prop변수를 더 앞에서 선언하고 316,340,342줄 바꿔놓겠습니다!

2021-11-03 03:28 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +        prop.remember_username = read_remembered_checkbox()
1. 요건 맨처음 실행했을때 체크박스가 켜진 상태로 보여주는게 좋을거 같아서 넣었습니다.
if문이 없으면 처음 킨 상태에선 username파일이 없기 때문에 체크박스가 꺼진 상태로 유저에게 보여줘서 추가했습니다.
2. 말씀하신대로 위에서 확인하기 때문에 내용을 try 블록 안으로 옮기겠습니다!

2021-11-03 03:48 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +        prop.username = read_remembered_id()
앗 넵 342번줄을 삭제하겠습니다!

2021-11-03 04:53 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +                row.prop(
넵 다른분들께서도 아이콘만 있는 경우에 무슨 기능인지 모르겠다고 하셔서 호이님께서 주신 이미지 안으로 변경했습니다!

2021-11-03 04:57 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +                row.prop(
엇 이부분 기작은 하는데 다른 언어로 번역이 안되네요..! 번역은 혹시 어떤 코드를 넣어야할까요??

2021-11-03 05:50 UTC, seungha-kim commented on release/scripts/startup/bl_operators/wm.py
> +                row.prop(
요거 설명 못들으셨으면 제가 세시반쯤 설명 드릴게용

2021-11-03 05:51 UTC, Youdiie commented on release/scripts/startup/bl_operators/wm.py
> +                row.prop(
앗 감사합니다 댄님!

2021-11-03 06:45 UTC, Youdiie commented
snip render merge로 rebase 했습니다!
호이님 리뷰해주신 내용 수정완료했습니다

2021-11-03 17:15 UTC, hoiekim commented on release/scripts/startup/abler/credential_modal.py
> +        prop.remember_username = read_remembered_checkbox()
> path_cookiesFile은 "acon3d_session" 파일인데 이 세션데이터가 존재할 경우에만 remembered_id를 확인하는 것이 맞나요??

"acon3d_session" 파일이 아닌 "username" 파일을 확인하려면 `os.path.isfile(path_cookiesFile)`이 아니라 `os.path.isfile(".../cookies/username")`으로 실행해야 할 것 같습니다.

2021-11-03 17:17 UTC, hoiekim commented on release/scripts/startup/abler/lib/remember_id.py
> +path_cookiesID = os.path.join(path_cookiesFolder, "userID")
함수 이름도 `remembered_id` 말고 `remembered_username`으로 변경하면 어떨까요??

2021-11-04 00:38 UTC, Youdiie commented on release/scripts/startup/abler/lib/remember_id.py
> +path_cookiesID = os.path.join(path_cookiesFolder, "userID")
넵 함수 이름도 바꾸겠습니다!

2021-11-04 00:52 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +        prop.remember_username = read_remembered_checkbox()
username 파일은 read_remembered_checkbox()에서 확인하고 있습니다! 
acon3d_session 파일을 확인한 이유는 맨 처음 에이블러를 실행했을 때 acon3d_session파일이 없으면 맨 처음 실행한 상태임을 알고 체크박스를 default=True로 반환하기 위해서 입니다.
acon3d_session파일이 있으면 이전에 로그인을 했었던 흔적이 있기 때문에 그때 username파일의 여부에 따라 체크박스를 켜냐,끄느냐를 반환하도록 했습니다.

2021-11-04 00:55 UTC, Youdiie commented
호이님 말씀해주신 함수에서 'ID' -> 'username' 변경했습니당

2021-11-04 20:26 UTC, hoiekim commented on release/scripts/startup/abler/credential_modal.py
> +        prop.remember_username = read_remembered_checkbox()
아하... 이해했습니다. 좋습니다!

2021-11-04 20:27 UTC, hoiekim approved these changes

2021-11-04 23:14 UTC, merged