Feature/login_enter
acon3d/ABLER pull request #140
Opened 2021-11-08 04:42 UTC by Youdiie

더블엔터 로그인 기능과 아이디,패스워드를 입력하고 지울 수 있는 버튼을 추가했습니다.

2021-11-08 06:44 UTC, Youdiie commented
"Username" subtype을 C에서 생성, prop.username과 prop.password에 넣었습니다.
 interface_handlers.c 파일에서 event_add 부분 주석처리하고 올렸습니다.

2021-11-08 07:16 UTC, seungha-kim requested changes

2021-11-08 07:16 UTC, seungha-kim commented on source/blender/editors/interface/interface_handlers.c
> +#ifdef WITH_INPUT_IME
이 파일의 변경사항은 필요없는 것 맞죵?

2021-11-08 07:18 UTC, Youdiie commented on source/blender/editors/interface/interface_handlers.c
> +#ifdef WITH_INPUT_IME
필요없다기보단 저 부분을 스듴님이랑 고민하다가 기록용으로 다시 보기위해 남겨두었습니다!

2021-11-08 07:20 UTC, seungha-kim commented on source/blender/editors/interface/interface_handlers.c
> +#ifdef WITH_INPUT_IME
아아 이해했슴다! 저는 이런 류의 기록은 노션이나 개인 브랜치에 남겨두는 편이고, 배포될 코드에는 남겨두지 않는 편인데 다른 분들은 어떠신지 궁금함당

2021-11-08 07:22 UTC, sdkfile commented on source/blender/editors/interface/interface_handlers.c
> +#ifdef WITH_INPUT_IME
저는 같이 고민한 흔적들은 좀 남겨놔서 나중에 참고하는 방향이 좋다고 생각합니다 :)

2021-11-08 07:23 UTC, sdkfile reviewed
이거는 한타임 쉬었다가 엔터로 한번에 로그인 하는 코드 완성되면 PR 마무리 짓는게 어떨까요? 

필요하시다면 저도 이 기능에 투입되어도 괜찮을 것 같아요

2021-11-08 07:25 UTC, Youdiie commented
> 이거는 한타임 쉬었다가 엔터로 한번에 로그인 하는 코드 완성되면 PR 마무리 짓는게 어떨까요?
> 
> 필요하시다면 저도 이 기능에 투입되어도 괜찮을 것 같아요

2021-11-08 07:26 UTC, Youdiie commented
> 이거는 한타임 쉬었다가 엔터로 한번에 로그인 하는 코드 완성되면 PR 마무리 짓는게 어떨까요?
> 
> 필요하시다면 저도 이 기능에 투입되어도 괜찮을 것 같아요

2021-11-08 07:28 UTC, sdkfile commented
> 억 잘못눌렀습니다.. 죄송합니다!

어어? 짜증낸건가요? 어어?? ㅋㅋㅋㅋ

2021-11-08 07:34 UTC, seungha-kim commented on source/blender/editors/interface/interface_handlers.c
> +#ifdef WITH_INPUT_IME
흐흐 그러면 주석에 의도가 포함이 되면 좋을 것 같슴다!

2021-11-08 07:35 UTC, Youdiie commented on source/blender/editors/interface/interface_handlers.c
> +#ifdef WITH_INPUT_IME
넵 주석으로 내용 보충해서 커밋하겠습니다!

2021-11-08 18:26 UTC, hoiekim commented on release/scripts/startup/abler/custom_properties.py
> +        subtype="USERNAME",
`USERNAME` subtype이 부여하는 성질이 어떤 것인지 제가 잘 파악하지 못했습니다.. password_shown 속성이 `USERNAME` 타입인 것이 명목적으로 어색한 느낌이 드는데 어떤 의도인가요??

2021-11-16 06:54 UTC, sdkfile commented
보류중인 태스크는 일단 닫고 추후에 리오픈 합니다

2021-11-16 06:54 UTC, closed without merging