tracing fly button in general
ACON3D/ABLER pull request #17
Opened 2021-11-26 04:28 UTC by Youdiie

general 패널에 있는 fly 버튼 tracker를 만들었습니다. camera control 패널에 있는 fly 버튼과 구분하기 위해 변수명을 "fly_in_general"로 설정했습니다.

2021-11-29 02:57 UTC, seungha-kim commented on release/scripts/startup/abler/general.py
> +class FlyOperator(bpy.types.Operator):
오오 앞으로 블렌더 내장 오퍼레이터를 호출하는 UI인 경우 트래킹을 위해 이렇게 한번 감쌀 일이 꽤 생길 것 같네용~~ 좋슴다!

2021-11-29 02:57 UTC, seungha-kim commented on release/scripts/startup/abler/general.py
> +    bl_idname = "acon3d.flymode1"
`flymode1` 에서 1은 무슨 의미인가용?

2021-11-29 03:00 UTC, sdkfile commented on release/scripts/startup/abler/general.py
> +    bl_idname = "acon3d.flymode1"
그러게요... 저도 궁금

2021-11-29 03:08 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +    bl_idname = "acon3d.flymode1"
애나님 노션보드 보니까 fly1, fly2(Object패널)로 구분했길래 저렇게 했습니당

2021-11-29 03:11 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +class FlyOperator(bpy.types.Operator):
살짝 걱정되는건 operator마다 호출시 조건을 달아주는게(144줄) 달라서 이 점 유의해야 할거 같습니다!

2021-11-29 03:13 UTC, seungha-kim commented on release/scripts/startup/abler/general.py
> +    bl_idname = "acon3d.flymode1"
아항 이해했슴다 ㅎㅎ 제 생각에는 "오로지 트래킹을 위해서만 존재하는 코드" (_tracker.py 라던가) 가 아닌 부분에서는, 코드 가독성을 위해 트래킹 관련 문서를 따르지 않고 저희한테 좋은 이름을 정해서 쓰는게 좋을 것 같아요. `acon3d.fly_in_general` 이라던가? 어떤 이름이 좋을까용?

그나저나 애나님 문서에서 fly1 과 fly2 의 차이점이 뭔지도 궁금하네용

2021-11-29 04:51 UTC, Youdiie commented on release/scripts/startup/abler/general.py
> +    bl_idname = "acon3d.flymode1"
아마 fly1은 General 패널, fly2는 Object 패널에 있는걸 말하는거 같습니다!
넵 _tracker.py에서도 fly_in_general로 정의해서 `acon3d.fly_in_general` 가 좋은거 같습니당

2021-12-01 01:52 UTC, sdkfile requested changes
단축키가 `acon3d.fly_in_general` 로 가도록 키매핑을 수정해야함

2021-12-01 08:09 UTC, Youdiie commented
단축키와 Camera control 패널에 있는 fly도 같은 acon3d.fly_mode 오퍼레이터로 기작함으로써 트래킹이 가능케 했습니다.
추가적으로 에이블러에 있는 모든 fly를 acon3d.fly_mode 오퍼레이터로 통일시켜서 네이밍을 fly_in_general에서 fly_mode로 변경했습니다!

2021-12-01 08:11 UTC, sdkfile commented
@Youdiie 단축키 관련해서 바뀐부분이 푸시가 안된 것 같은데 맞을까요?

2021-12-01 08:34 UTC, sdkfile approved these changes
확인했습니다!

2021-12-01 09:10 UTC, Youdiie commented
앗 요거 잠깐 중단할께요!

2021-12-01 09:24 UTC, Youdiie commented
아까 계속 안됐던 부분이 black이 적용되면서 stage lines가 아예 틀어져버려서 오류가 났던거 같습니다,,, 단축키 들어가는 abler_default.py는 black이 작동하지 않아야 할거 같아요! 그부분 다시 수정했습니다!

2021-12-01 09:28 UTC, sdkfile submitted a review, later dismissed
블랙이 원인이었군요! 블랙 ignore 파일같은게 있어야 할 것 같네용

2021-12-01 09:31 UTC, sdkfile commented
@Youdiie fmt on off 추가해주시면 어프룹 가겠습니당!

2021-12-07 01:13 UTC, sdkfile approved these changes

2021-12-07 01:14 UTC, seungha-kim approved these changes

2021-12-07 01:14 UTC, merged