Feature/mixpanel/tracker file open
ACON3D/ABLER pull request #25
Opened 2021-12-06 01:04 UTC by Youdiie

tracker를 심은채로 file open 오퍼레이터를 새로 만들어 우측 패널의 버튼과 단축키(ctrl+O)에서 트래킹이 되도록 설정했습니다.

오퍼레이터에 tracker를 심은 상태로는 윈도우 창에서 파일을 더블클릭 시 open 트래킹을 할수 없어, 에이블러 런처를 실행할 시 파일명을 확인하여 빈 문자열(런처로 실행시엔 파일명은 빈 문자열)이 아닐경우 open으로 간주하고 트래킹을 하도록 추가했습니다.

2021-12-06 01:08 UTC, Youdiie commented
파일 오픈 오퍼레이터에 tracker도 심어주면 오픈 버튼을 눌러서 실행시 TRACKING: File Open이 두번 되네요. 오퍼레이터에선 tracker를 빼줘야할거 같습니다.

![image](https://user-images.githubusercontent.com/87409148/144772044-fdc4cb41-e9f5-4235-aab5-46647ae6e7a4.png)
다만 단축키에 오퍼레이터를 연동해주니 버튼에 커서를 댔을때 단축키 설명이 같이 떠서 요건 탑재해도 좋을거 같습니다!

2021-12-07 01:37 UTC, seungha-kim commented on release/scripts/startup/abler/credential_modal.py
> +        tracker.file_open()
"파일을 열 때마다 open_credential_modal 이 호출된다" 는 가정하에 짜여진 코드인데, 나중에 놓치기 쉬운 부분으로 보여서, 의도가 좀 더 잘 드러나게 `post_file_open` 혹은 `post_window_open` 등의 함수로 한번 더 해당 내용을 감싸서 open_credential_modal은 그걸 호출하게 만들면 좋을 것 같습니다.

2021-12-07 02:29 UTC, seungha-kim requested changes
request changes 로 돌려놓슴당

2021-12-07 02:58 UTC, Youdiie commented
추후에 에이블러 오픈 시 들어갈 기작들을 모아두면 좋을 거 같아 lib 폴더에 post_open.py를 만들고 그 안에 함수로 tracker_file_open을 감싸주었습니다.

2021-12-07 04:27 UTC, seungha-kim approved these changes

2021-12-07 04:39 UTC, sdkfile approved these changes

2021-12-07 04:39 UTC, merged