open with view_transform "Standard"
ACON3D/ABLER pull request #42
Opened 2021-12-20 04:20 UTC by Youdiie

파일 오픈 시 view transform을 자동으로 "Standard"로 바꿔주도록 기작을 추가해주었습니다.

2021-12-22 08:23 UTC, seungha-kim approved these changes
어프룹임다!

2021-12-23 01:23 UTC, sdkfile requested changes

2021-12-23 01:23 UTC, sdkfile commented on release/scripts/startup/abler/pref.py
> +    bpy.context.scene.view_settings.view_transform = "Standard"
이부분 load_handler로 옮겨주세용

2021-12-23 01:24 UTC, hoiekim commented on release/scripts/startup/abler/pref.py
> +    bpy.context.scene.view_settings.view_transform = "Standard"
```
for scene in bpy.data.scenes:
  scene.view_settings.view_transform = "Standard"
```

2021-12-23 02:47 UTC, Youdiie commented on release/scripts/startup/abler/pref.py
> +    bpy.context.scene.view_settings.view_transform = "Standard"
아하 scene이 여러개 있을 경우도 있겠네요! 호이님 감사합니다 :)

2021-12-23 02:57 UTC, sdkfile approved these changes
확인했고 어프룹 후 머지 바로 가겠습니다!

2021-12-23 02:57 UTC, merged