separate file open & login auto
ACON3D/ABLER pull request #49
Opened 2021-12-24 04:44 UTC by Youdiie

1. File Open과 Login Auto를 나누었습니다. 파일을 열때 기본 '코니방'이 뜨면 `bpy.data.filepath`에서 ""(빈 문자열)이 뜹니다. 요걸 이용해 File Open 버튼이나 파일을 더블클릭해서 열면 `bpy.data.filepath != ""`이 돼서 file open이라고 인식하고 tracker.file_open()을 실행합니다.

2. Login Auto가 맨 처음 에이블러를 실행했을때만 트래킹되고 창이 열려있는 상태에서 또 에이블러를 킨다면(주로 파일을 더블클릭해서 열때) Login Auto가 트래킹되지 않도록 했습니다. 에이블러를 실행했을 때 시스템 환경창(윈도우에선` subprocess.check_output(["tasklist"]),` 맥에선 `os.popen("ps -Af"))`에서 에이블러가 켜져있는지(윈도우에선 에이블러 실행 시 blender로 떠서 추가했습니다) 확인하고 이미 켜져있다면 Login Auto를 하지 않도록 기작했습니다.

2021-12-24 05:07 UTC, sdkfile requested changes
리뷰 1차 완료했습니다!

2021-12-24 05:07 UTC, sdkfile commented on release/scripts/startup/abler/lib/login.py
> +        proccount = tmp.count("ABLER")
`proccount` 보다는 `process_count`로 가는게 더 알아보기 편할 것 같습니다! 추가적으로 위에 있는 `cnt`와 `proccount`가 같은 맥락의 것이고, `platform.system()` if문은 동시에 통과할 수 없으니 `cnt`도 `process_count`로 가주는게 좋을 것 같습니다!

2021-12-24 05:07 UTC, sdkfile commented on release/scripts/startup/abler/lib/login.py
> +        tmp = os.popen("ps -Af").read()
`tmp`는 쓰임새가 내용 전달밖에 없으니 아래 코드를
```
proccount = os.popen("ps -Af").read().count("ABLER")
```
로 가는게 어떨까요?

2021-12-24 05:07 UTC, sdkfile commented on release/scripts/startup/abler/credential_modal.py
> +                if is_first_open():
여기 그냥 and 써서 조건 쓰는게 더 가독성이 좋지 않을까요?
```
if (not fileopen) and is_first_open():
```
이런식으로요!

2021-12-24 05:45 UTC, Youdiie commented on release/scripts/startup/abler/lib/login.py
> +            return True
리스트 컴프리핸션은 볼때마다 감탄나오네요.. 너무 좋습니다!

2021-12-24 05:49 UTC, Youdiie commented on release/scripts/startup/abler/lib/login.py
> +        tmp = os.popen("ps -Af").read()
넵 요게 훨씬 간결하고 좋은거 같습니다!

2021-12-24 05:50 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +                if is_first_open():
오 그렇네요! 이중 if문은 and로 묶는 방법이 있군요!

2021-12-24 05:58 UTC, Youdiie commented
스듴님 리뷰 반영해서 수정했습니다!

2021-12-24 07:01 UTC, seungha-kim commented on release/scripts/startup/abler/lib/login.py
> +            .decode("cp949", "ignore")
앗... cp949는 윈도 한국어에서만 쓰이는 인코딩인데 다른 언어에서 괜찮을지 모르겠네용

2021-12-24 07:10 UTC, seungha-kim commented on release/scripts/startup/abler/lib/login.py
> +            bool(i.startswith("blender") or i.startswith("ABLER") for i in p)
bool 에다가 sum 을 돌리면 에러가 날 것 같은 느낌임다!

그리고 `bool(...)` 안에 있는 객체가 이터레이터이기 때문에 `bool(...)` 요놈이 항상 True 가 나올겁니다.

`bool(False for i in range(10))` 이 코드로 실험해봤어용

2021-12-24 07:11 UTC, sdkfile commented on release/scripts/startup/abler/lib/login.py
> +            bool(i.startswith("blender") or i.startswith("ABLER") for i in p)
앗 bool 빼야겠네용

2021-12-24 07:11 UTC, sdkfile commented on release/scripts/startup/abler/lib/login.py
> +            .decode("cp949", "ignore")
디코딩을 utf8로 하면 괜찮으려나요 그럼?

2021-12-24 07:11 UTC, seungha-kim commented on release/scripts/startup/abler/lib/login.py
> +            bool(i.startswith("blender") or i.startswith("ABLER") for i in p)
그리고 중요한 문제는 아니지만, 찐 블렌더가 켜져 있다면 이 코드가 영향을 받기는 하겠네요.

만약 그래도 괜찮다면, 주석을 남겨두는게 좋을 것 같슴다!

2021-12-24 07:13 UTC, seungha-kim commented on release/scripts/startup/abler/lib/login.py
> +            .decode("cp949", "ignore")
utf8 도 아닐 것 같은데, 한번 찾아볼게요

2021-12-24 07:14 UTC, sdkfile commented on release/scripts/startup/abler/lib/login.py
> +            bool(i.startswith("blender") or i.startswith("ABLER") for i in p)
모델러분이 사용을 하는 상황에서는 충분히 생길 수 있는 상황이긴 한 것 같습니당

2021-12-24 07:15 UTC, seungha-kim commented on release/scripts/startup/abler/lib/login.py
> +            bool(i.startswith("blender") or i.startswith("ABLER") for i in p)
오오 딱 bool 만 빼면 되는 거네용. bool 배열에 sum 할 수 있는거 배우고 갑니당

2021-12-24 07:19 UTC, seungha-kim commented on release/scripts/startup/abler/lib/login.py
> +            .decode("cp949", "ignore")
https://stackoverflow.com/questions/37506535/how-to-get-the-system-default-encoding-in-python-2-x/37506634

일단 `sys.stdin.encoding` 요걸로 동적으로 OS 인코딩 방식을 가져올 수 있는 듯합니다!

2021-12-24 07:40 UTC, seungha-kim commented on release/scripts/startup/abler/lib/login.py
> +            .decode("cp949", "ignore")
이 로직을 직접 작성할 때 애매한 부분이 있으니, 라이브러리 쓰는 것도 방법일 듯 합니다!
찾아보니 psutil 이라는게 있네요

https://stackoverflow.com/a/7788702
https://github.com/giampaolo/psutil

2021-12-24 10:03 UTC, Youdiie commented
psutil을 쓰니 윈도우, 맥 구분없이 바로 확인할 수 있습니다!
다만, 윈도우에선 에이블러를 "blender.exe"로 인식해서 댄님께서 말씀하신 것처럼 찐 블렌더가 켜져 있다면 영향을 받긴 할거 같습니다🥲 주석 남겨놓았습니다!

2021-12-24 10:06 UTC, seungha-kim approved these changes
사소한거 달아놓은 거 외에는 어프룹임다!! 고생 많으셨어용!

2021-12-24 10:06 UTC, seungha-kim commented on release/scripts/startup/abler/lib/login.py
> +import re, os
사소한 거지만, re, os, subprocess, platform 은 지워도 되겠네용

2021-12-24 10:12 UTC, Youdiie commented on release/scripts/startup/abler/lib/login.py
> +import re, os
아이고ㅋㅋㅋ 바로 수정해놓겠습니닷!

2021-12-28 01:40 UTC, Youdiie commented on release/scripts/startup/abler/lib/login.py
> +        i.startswith("ABLER") or i.startswith("blender")
소문자 abler 추가!

2021-12-28 02:14 UTC, Youdiie commented
추후 abler.exe로 만들 경우를 대비해 "abler" 추가했습니다!

2021-12-28 02:22 UTC, sdkfile approved these changes
어프룹임다~

2021-12-28 02:23 UTC, merged