Add scene save/delete/select + presets feature
acon3d/ABLER pull request #5
Opened 2021-08-10 22:04 UTC by hoiekim

2021-08-11 02:37 UTC, sdkfile reviewed
빌드 테스트랑 다 진행해봤는데 다 잘 되는 것 같습니다!
그런데 이 기능 관련해서 ko.po에 번역 파일 추가해주시고나서 머지하는게 좋을 것 같습니다!
기능적으로 아쉬운게 있다면 씬 리네임 기능이 없는거네용 (추후 업데이트 내용으로 가져가면 좋을 것 같습니다!)

2021-08-11 02:58 UTC, sdkfile requested changes
Request changes로 올리는걸 깜빡했네용 ㅎ

2021-08-11 17:33 UTC, hoiekim commented
> 빌드 테스트랑 다 진행해봤는데 다 잘 되는 것 같습니다!
> 그런데 이 기능 관련해서 ko.po에 번역 파일 추가해주시고나서 머지하는게 좋을 것 같습니다!
> 기능적으로 아쉬운게 있다면 씬 리네임 기능이 없는거네용 (추후 업데이트 내용으로 가져가면 좋을 것 같습니다!)

아래 스크린샷과 같이 씬 생성시 이름 입력하도록 UI 추가해보았습니다.. 그런데 한국어를 입력하면 에러가 떠서 이번에 도입하지 않고 나중에 해결 보는 것으로 재검토 제안합니다... ㅠㅠ

![image](https://user-images.githubusercontent.com/61715204/129075702-b4d79703-e7c4-4b09-9e80-5860db83c380.png)
![image](https://user-images.githubusercontent.com/61715204/129075940-7682e71c-3d42-4612-84d0-997cdfef5497.png)

2021-08-13 01:13 UTC, sdkfile approved these changes

2021-08-13 01:13 UTC, merged