믹스패널 국가별 트래킹
ACON3D/ABLER pull request #67
Opened 2022-01-21 06:13 UTC by Youdiie

![스크린샷 2022-01-21 오후 3 08 42](https://user-images.githubusercontent.com/87409148/150475519-c86382b0-28c4-4090-8b5a-df802f4315bc.png)
get_ip 함수에서 `try : ip = get("https://api.ipify.org").text`로 ip를 받아오고 _mixpanel.py의 _enqueue_email_update 함수에 ip를 meta데이터에 심어주면 믹스패널에서 자동으로 국가별 트래킹을 해줍니닷!

2022-01-21 08:33 UTC, seungha-kim requested changes

2022-01-21 08:33 UTC, seungha-kim commented on release/scripts/startup/abler/lib/tracker/_tracker.py
> +    def login(self, email: str, ip: str):
login 이벤트를 트래킹하는 함수에 ip 파라미터가 있는게 이상하네용 ㅎㅎ 제가 짜놓은 처음 구조가 조금 이상한듯

제 생각에는 login 함수는 진짜 login 이벤트를 트래킹하는 걸로 바꾸고 (그러니까 아무 파라미터도 받지 말고),
update_profile 같은 이름의 함수를 새로 만들어서 그걸 통해서 email 과 ip 를 둘 다 넣어주는게 어떨까 싶어용.

2022-01-21 08:33 UTC, seungha-kim commented on release/scripts/startup/abler/credential_modal.py
> +        tracker.login(self.username, ip=get_ip())
여기가 아래처럼 바뀌면 좋을 것 같습니다

```
tracker.login()
tracker.update_profile(self.username)
```

`ip를 얻어온다` 는 세부사항은 credential_modal 에서 알 필요 없는 내용이니 트래커에 숨기는게 좋을 듯 합니다!

2022-01-21 08:33 UTC, sdkfile requested changes
위 코멘트 말고는 추가 코멘트 없습니다 고생하셨습니다!

2022-01-21 08:33 UTC, sdkfile commented on release/scripts/startup/abler/lib/tracker/_get_ip.py
> +        ip = get("https://api.ipify.org").text
ip라는 변수는 사용되는 변수가 아니니, `return get("https://api.ipify.org").text` 라고만 해도 괜찮지 않을까요?

2022-01-21 08:47 UTC, Youdiie commented on release/scripts/startup/abler/lib/tracker/_tracker.py
> +    def login(self, email: str, ip: str):
오오 그렇게 분리하면 함수명으로 직관적으로 이해하기 좋을거 같습니다!
요렇게 변경해 보겠습니다 :)

2022-01-21 08:47 UTC, Youdiie commented on release/scripts/startup/abler/lib/tracker/_get_ip.py
> +        ip = get("https://api.ipify.org").text
넵 요것도 반영하겠습니다!

2022-01-21 08:55 UTC, Youdiie commented
댄님, 스듴님 코멘트해주신 내용대로 수정했습니다!
코멘트 편하게 부탁드립니다아

2022-01-21 09:00 UTC, sdkfile approved these changes
어프룹입니다!!

2022-01-21 09:00 UTC, seungha-kim requested changes

2022-01-21 09:00 UTC, seungha-kim commented on release/scripts/startup/abler/lib/tracker/_tracker.py
>          Enqueue update of user email.
요기 주석 포함 _enqueue_email_update 라는 함수 이름도 같이 바꾸면 좋을 것 같슴다 ㅎㅎ _enqueue_profile_update 어떨까요?

2022-01-21 09:49 UTC, Youdiie commented on release/scripts/startup/abler/lib/tracker/_tracker.py
>          Enqueue update of user email.
넵! 주석내용은 Enqueue update of user email and get ip. 요렇게 어떠신가용?

2022-01-21 09:56 UTC, seungha-kim commented on release/scripts/startup/abler/lib/tracker/_tracker.py
>          Enqueue update of user email.
get 빼고 Enqueue update of user email and ip. 로 가시죵~

2022-01-21 09:59 UTC, Youdiie commented on release/scripts/startup/abler/lib/tracker/_tracker.py
>          Enqueue update of user email.
죠습니다~

2022-01-21 10:01 UTC, Youdiie commented
어..어프룹..!?

2022-01-21 10:07 UTC, seungha-kim requested changes

2022-01-21 10:07 UTC, seungha-kim commented on release/scripts/startup/abler/lib/tracker/_get_ip.py
> +def get_ip() -> str:
딱 하나만 더 ㅋㅋㅋㅋ 이거 리턴 타입을 str 로 하셨는데 실제로는 Optional[str] 이잖아요? (에러가 나면 리턴값이 없으니까)

일단 타입 어노테이션은 Optional[str] 로 수정되어야 하고, 또 실제로 None 이 리턴됐을 때 혹시 다른 부분에서 문제가 생기지 않는지 한 번은 검사가 필요할 것 같습니다! (강제로 None 리턴하도록 하드코딩한 다음에 동작여부랑 믹스패널 검사) 요건 다음주에 하셔도 될 것 같아요!!

2022-01-21 10:08 UTC, seungha-kim commented on release/scripts/startup/abler/lib/tracker/_get_ip.py
> +def get_ip() -> str:
왜 한번에 안 보이는지... 죄송함다 흑흑

2022-01-21 10:17 UTC, Youdiie commented on release/scripts/startup/abler/lib/tracker/_get_ip.py
> +def get_ip() -> str:
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ갠찬습니다! 편하게 코멘트 남겨주세요 :) 
요건 그럼 다음주의 저에게 토스하겠습니다..ㅎㅎ

2022-01-24 02:17 UTC, Youdiie commented
Optional[str]로 수정한뒤 `return None`, `없는 주소로 request`했을때도 error없이 잘 작동하는거 확인했습니다!

2022-01-24 02:19 UTC, seungha-kim approved these changes
어프룹임다! 고생많으셨어요!

2022-01-24 02:19 UTC, merged