Improve state UI
ACON3D/ABLER pull request #7
Opened 2021-11-22 19:40 UTC by hoiekim

This PR creates following changes to UI

1. Turning on `Use State` moves state slider to 1.0
2. Turning off `Use State` moves state slider to 0.0
3. Turning off `Use State` does not remove state data
4. `Update State` button moves state slider to 1.0, updates `end_state` instead of `mid_state`

2021-11-23 06:54 UTC, Youdiie commented on release/scripts/startup/abler/lib/objects.py
> +    use_state = self.use_state
custom_properties에서 use_state를 정의할 때 update에서 toggleUseState를 받기때문에 51번줄에서 context.object.Acon_prop.use_state가 self로 바껴도 되는걸까요? 기능에서 차이는 없는거죠?

2021-11-23 06:54 UTC, Youdiie commented on release/scripts/startup/abler/object_control.py
> +    @classmethod
요 클래스매서드가 개체가 선택돼 있을때만 작동이 가능하게 하는 기능이었죠? 에이블러에선 sun이나 camera를 직접선택할 일이 없지만 우연히 sun,camera가 선택이 됐을때도 use_state가 실행이 될 수 있을거 같습니다!

2021-11-23 10:32 UTC, sdkfile commented on release/scripts/startup/abler/object_control.py
> +    @classmethod
오 이건 저도 그렇게 생각합니당

2021-11-23 10:33 UTC, sdkfile requested changes
> 요 클래스매서드가 개체가 선택돼 있을때만 작동이 가능하게 하는 기능이었죠? 에이블러에선 sun이나 camera를 직접선택할 일이 없지만 우연히 sun,camera가 선택이 됐을때도 use_state가 실행이 될 수 있을거 같습니다! 

저는 이부분 에외처리만 들어가면 괜찮을 것 같습니다!

2021-11-24 01:54 UTC, hoiekim commented on release/scripts/startup/abler/object_control.py
> +    @classmethod
Sun, Camera 오브젝트들도 자유롭게 state를 사용하면 유용할 것 같습니다. :)

2021-11-24 01:59 UTC, hoiekim commented on release/scripts/startup/abler/lib/objects.py
> +    use_state = self.use_state
이 함수는 반드시 update될 때만 실행된다고 가정하면 `self.use_state`는 use_state가 업데이트되었을 때 업데이트된 그 속성값을 가집니다. 반면 `contet.object.ACON_prop.use_state`는 어느 use_state값이 변경되었는지 상관 없이 항상 마지막에 선택된 오브젝트의 use_state값을 가집니다.

패널에서 유저가 조작하는 use_state 값은 항상 마지막에 선택된 오브젝트의 use_state값이기 때문에 기존에는 `contet.object.ACON_prop.use_state`를 사용했지만 원칙적으로는 올바르지 않고 특정 상황에서 의도하지 않은 모습으로 동작하기 떄문에 `self.use_state`로 변경하였습니다.

2021-11-24 06:14 UTC, Youdiie commented on release/scripts/startup/abler/object_control.py
> +    @classmethod
앗 그렇게 의도하신거군요! 감사합니다ㅎㅎ

2021-11-24 06:17 UTC, Youdiie approved these changes

2021-11-25 08:33 UTC, sdkfile commented on release/scripts/startup/abler/object_control.py
> +    @classmethod
@hoiekim 앗 그럼 저도 이해했습니다!

2021-11-25 08:33 UTC, sdkfile approved these changes

2021-11-25 08:33 UTC, merged