change any value when file open
ACON3D/ABLER pull request #75
Opened 2022-01-25 05:52 UTC by Youdiie

애나님 말씀에 힌트를 얻어 pref.py에서 `change_and_reset_value()`함수를 넣어주었습니다.
아마도 `materials_setup.applyAconToonStyle()`에서 노드를 바꿔주고 블렌더가 업데이트를 하지 못해서 발생한 에러인거 같습니다!

2022-01-25 06:15 UTC, sdkfile requested changes
잔잔바리로 수정할 사항이 있는 것 같습니다~~

2022-01-25 06:15 UTC, sdkfile commented on release/scripts/startup/abler/lib/pre_open.py
> +    # 아무 레이어나 변경했다가 다시 리셋
레이어가 아니고 씬 아닐까요!! 주석 수정해주시면 좋을 것 같습니다!

2022-01-25 06:15 UTC, sdkfile commented on release/scripts/startup/abler/lib/pre_open.py
> +    print("A!!")
프린트도 빼주시면 좋을 것 같아요~

2022-01-25 06:15 UTC, sdkfile commented on release/scripts/startup/abler/credential_modal.py
> +from .lib.pre_open import tracker_file_open
음.. 원래 있던 post_open을 pre_open으로 바꾼 이유가 있을까요? 안에 있는 코드를 보니깐 `pref.py` 에 있는 `init_setting`도 어쨌든 `load_factory_startup_post` 핸들러에 묶여 있는 기작이라서 파일 오픈 후에 작용되는 파일일텐데 post_open을 그대로 유지하는 방향이 좋을 것 같습니다!

2022-01-25 06:18 UTC, Youdiie commented on release/scripts/startup/abler/lib/pre_open.py
> +    print("A!!")
헉ㅋㅋㅋㅋㅋㅋㅋ 맘이 급했네요🥲

2022-01-25 06:19 UTC, Youdiie commented on release/scripts/startup/abler/lib/pre_open.py
> +    # 아무 레이어나 변경했다가 다시 리셋
패널값이라 레이어라고 생각했는데 씬이군요! 감사합니당

2022-01-25 06:22 UTC, Youdiie commented on release/scripts/startup/abler/credential_modal.py
> +from .lib.pre_open import tracker_file_open
앗 수정할때는 open전에 하는 기작이라 생각해서 변경했는데 스듴님 말씀 듣고보니 파일 오픈 후에 작용하는 파일들에 더 가깝겠네요! post_open으로 수정해놓겠습니다~

2022-01-25 06:54 UTC, sdkfile approved these changes
어프룹입니다!

2022-01-26 07:00 UTC, seungha-kim approved these changes
코멘트 달아놓은거는 사소한거라 할지말지 선택은 유디님에게 맡깁니다 ㅎㅎ

어프룹임다!

2022-01-26 07:08 UTC, sdkfile commented on release/scripts/startup/abler/pref.py
> +    change_and_reset_value()
오우 좋습니당

2022-01-26 07:12 UTC, Youdiie commented on release/scripts/startup/abler/pref.py
> +    change_and_reset_value()
오우 넵!

2022-01-26 07:16 UTC, merged