drag-and-drop
ACON3D/ABLER pull request #77
Opened 2022-01-25 08:31 UTC by Youdiie

1. 파일 드래그앤드랍에 import 기능 심기
2. 윈도우에서 런쳐로 에이블러 실행시 블렌더를 관리자권한 없이 실행하도록 AblerLauncher.py 수정

2022-01-25 08:43 UTC, sdkfile requested changes
마이너한 수정사항입니당~~

2022-01-25 08:43 UTC, sdkfile commented on launcher_abler/lib.py
> +if __name__ == "__main__":
이건 빠져도 될 것 같습니당 
어차피  main function으로 사용되는 녀석이 아니고 헬퍼 함수로만 사용되는 녀석이니 266-267 번째 줄은 삭제 구다사이~~~

2022-01-25 08:43 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
> +import lib
그리고 얘를 그냥 lib이라고 하기엔 좀 기능이 specific 한 것 같아서 privilege_helper 등의 이름이 좀더 직관적일 것 같습니다!

2022-01-25 08:43 UTC, sdkfile commented on launcher_abler/AblerLauncher.py
> +                _ = lib.runas_shell_user(os.path.join('"' + dir_ + "/blender.exe" + '"'))
return된 값을 안쓰긴 하지만 혹시 모르니 뒤에 주석으로 `# pid와 tid를 리턴함` 정도 적어놓는게 어떨까요?

2022-01-25 08:51 UTC, Youdiie commented on launcher_abler/AblerLauncher.py
> +import lib
네이밍 어렵네요..

2022-01-25 09:21 UTC, sdkfile approved these changes
아까 lib.py에서 black 안돌았었나보네용
어프룹입니다!

2022-01-26 06:58 UTC, seungha-kim approved these changes
어프룹!

2022-01-26 07:16 UTC, merged